- aix360/algorithms/contrastive/CEM.py
- aix360/algorithms/contrastive/CEM_MAF.py
- aix360/algorithms/profwt/profwt.py
- aix360/algorithms/protodash/PDASH.py
Added more detailed descriptions and did more minor edits.
> Updated 4 algo files

- aix360/datasets/cifar_dataset.py
> CIFAR dataset update

- examples/profwt/Prof-Weight.ipynb
I changed all the refs according to the new directory structure and also added access through the dataset classes.
> Changes to Prof-Wt notebook

- examples/README.md
Fixing some of the broken example links in the example readme.
> Fix broken example links

- README.md
- aix360/algorithms/protodash/PDASH_utils.py
- aix360/datasets/heloc_dataset.py
> Updates to protodash and heloc data processing

- aix360/algorithms/ted/TED_Cartesian.py
Fixed the broken link to TED paper in comment
> Fix: modify broken link to TED paper

- aix360/algorithms/protodash/PDASH_utils.py
- setup.py
> protodash qp update

- aix360/algorithms/rbm/features.py
See issue #78 . It describes the problem and the resolution implemented in this pull request.
> Fix issue #78: FeatureBinarizer: data type cannot be handled

- aix360/algorithms/rbm/features.py
Resolves the issue for my dataset.
> one-liner for feature binarizer fixes #76

- aix360/algorithms/profwt/resnet_keras_model.py
- aix360/algorithms/profwt/train_probes.py
Removed duplicate license issue.
Removed commented codes.
> Changed train_probes.py and resnet_keras_model.py

- README.md
- setup.py
specified xgboost and lime versions dependencies in setup.py
> versions of dependent packages

- aix360/algorithms/rbm/beam_search.py
> Fix pandas duplicate axis issue (#97) in beam_search.py

- .travis.yml
- README.md
- setup.py
Forced h5py < 3.0 in setup.py due to h5py 3.0 & keras incompatibility issues.
> h5py + keras issues

- aix360/algorithms/rbm/features.py
- tests/rbm/test_Feature_Binarizer_From_Trees.py
Resolve unit test failures, future warnings, and a few minor compatibility issues relating to FeatureBinarizerFromTrees.
scikit-learn changed OneHotEncoder to support NaN instead of raising exception. This is incompatible with FeatureBinarizerFromTrees logic. FeatureBinarizerFromTrees.fit() checks for NaNs and raises exception. Relates to the following unit test failure.
Failure
Traceback (most recent call last):
File "tests/rbm/test_Feature_Binarizer_From_Trees.py", line 153, in     test_fit_and_transform_exceptions
fbt.fit(Xn, self.y_train)
AssertionError: ValueError not raised
numpy no longer raises warnings for NaN/None during vector comparisons. Removed unit test warning assertion. Relates to following unit test failure.
Failure
Traceback (most recent call last):
File …
> Update FeatureBinarizerFromTrees for compatibility with numpy 1.22.0, scikit-learn 1.0.2, and pandas > 1.3.

- aix360/algorithms/rbm/features.py
> improve column names of binary columns

- aix360/algorithms/rule_induction/rbm/boolean_rule_cg.py
- aix360/algorithms/rule_induction/rbm/utils.py
- tests/rule_induction/rbm/test_brcg.py
Provides BRCG explanations in the Technical Rule Exchange Format (TRXF) for compatibility with other rule induction methods.
> BRCG with TRXF outputs

- aix360/algorithms/gce/gce.py
- aix360/algorithms/nncontrastive/nncontrastive.py
- aix360/algorithms/tsice/tsice.py
- aix360/algorithms/tslime/tslime.py
- aix360/algorithms/tssaliency/gradient.py
- aix360/algorithms/tssaliency/tssaliency.py
- aix360/algorithms/tsutils/tsperturbers/block_bootstrap_perturber.py
This PR is fix format issues TS* explainer references and parameter documentation.
> format references and parameters 

- aix360/algorithms/gce/gce.py
- aix360/algorithms/nncontrastive/nncontrastive.py
- aix360/algorithms/tsice/tsice.py
- aix360/algorithms/tslime/tslime.py
- aix360/algorithms/tssaliency/tssaliency.py
docstring fixes in TS and Tabular explainers.
> docstring fixes

- setup.py
Allowing pandas version to use any version in 1.x.
> upgrade pandas to 1.x versions

- aix360/algorithms/nncontrastive/nncontrastive.py
- aix360/algorithms/tsice/tsice.py
- aix360/algorithms/tslime/tslime.py
- aix360/algorithms/tssaliency/tssaliency.py
- examples/gce/gce_demo.ipynb
- examples/tsice/tsice_demo.ipynb
- examples/tslime/tslime_multivariate_demo.ipynb
- examples/tslime/tslime_univariate_demo.ipynb
- examples/tssaliency/tssaliency_multivariate_demo.ipynb
- examples/tssaliency/tssaliency_univariate_demo.ipynb
Model and data support fixes in NNContrastive and TS* docstrings.
> Model and data support fixes in NNContrastive and TS* docstrings.
